name: yodacom
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6458685
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: YodaCom
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7149637036491185
  lightness: 0.732241707155481
  saturation: 0.461712081450969
  rhythmicContrast: 0.6603751440998167
purpose: []
